#!/bin/bash

# ==========================================
# Turnkey SaaS Platform Deployment Script
# Bash Version for Linux/Mac
# ==========================================
#
# This script automates the complete deployment of a full-stack SaaS platform to Cloudflare.
#
# Prerequisites:
# - Node.js installed
# - Git installed
# - Cloudflare account
# - Logged in via: npx wrangler login
#
# Usage:
#   ./deploy-turnkey.sh my-saas-app
#   ./deploy-turnkey.sh my-saas-app main
#
# ==========================================

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m' # No Color

# Helper functions
step() { echo -e "\n${CYAN}$1${NC}"; }
success() { echo -e "${GREEN}✅ $1${NC}"; }
error() { echo -e "${RED}❌ $1${NC}"; }
info() { echo -e "${YELLOW}ℹ️  $1${NC}"; }

# Check arguments
if [ -z "$1" ]; then
    error "Project name is required!"
    echo "Usage: ./deploy-turnkey.sh <project-name> [branch]"
    echo "Example: ./deploy-turnkey.sh my-saas-app main"
    exit 1
fi

PROJECT_NAME="$1"
BRANCH="${2:-main}"

echo -e "${MAGENTA}"
cat << "EOF"
╔══════════════════════════════════════════════════════════╗
║   🚀 Turnkey SaaS Platform Deployment                   ║
╚══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"
echo "Project: $PROJECT_NAME"
echo "Branch: $BRANCH"

# Check if logged in to Cloudflare
step "Checking Cloudflare authentication..."
if ! npx wrangler whoami &>/dev/null; then
    error "Not logged in to Cloudflare. Run: npx wrangler login"
    exit 1
fi
success "Authenticated with Cloudflare"

# Step 1: Create D1 Database
step "📊 Creating D1 Database: ${PROJECT_NAME}-db"
if npx wrangler d1 create "${PROJECT_NAME}-db" &>/dev/null; then
    success "D1 Database created"
else
    info "Database might already exist, continuing..."
fi

# Get database ID
info "Fetching database ID..."
DB_LIST=$(npx wrangler d1 list --json 2>/dev/null || echo "[]")
DB_ID=$(echo "$DB_LIST" | grep -o '"database_id":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$DB_ID" ]; then
    error "Could not find database ID. Please check Cloudflare dashboard."
    DB_ID="REPLACE_WITH_YOUR_DB_ID"
else
    success "Database ID: $DB_ID"
fi

# Step 2: Create R2 Bucket
step "📦 Creating R2 Bucket: ${PROJECT_NAME}-assets"
if npx wrangler r2 bucket create "${PROJECT_NAME}-assets" &>/dev/null; then
    success "R2 Bucket created"
else
    info "Bucket might already exist, continuing..."
fi

# Step 3: Create KV Namespace
step "🔑 Creating KV Namespace: CONFIG"
if npx wrangler kv namespace create CONFIG &>/dev/null; then
    success "KV Namespace created"
else
    info "KV namespace might already exist, continuing..."
fi

# Get KV ID
info "Fetching KV namespace ID..."
KV_LIST=$(npx wrangler kv namespace list --json 2>/dev/null || echo "[]")
KV_ID=$(echo "$KV_LIST" | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4)

if [ -z "$KV_ID" ]; then
    error "Could not find KV namespace ID. Please check Cloudflare dashboard."
    KV_ID="REPLACE_WITH_YOUR_KV_ID"
else
    success "KV Namespace ID: $KV_ID"
fi

# Step 4: Get Account ID
WHOAMI_OUTPUT=$(npx wrangler whoami 2>/dev/null || echo "")
ACCOUNT_ID=$(echo "$WHOAMI_OUTPUT" | grep -o 'Account ID: [a-f0-9]*' | awk '{print $3}')

if [ -z "$ACCOUNT_ID" ]; then
    info "Could not auto-detect account ID"
    ACCOUNT_ID="REPLACE_WITH_YOUR_ACCOUNT_ID"
fi

# Step 5: Update wrangler.toml
step "📝 Updating wrangler.toml configuration..."

cat > wrangler.toml << EOF
# Cloudflare Workers Configuration for ${PROJECT_NAME}
# Auto-generated by deploy-turnkey.sh

name = "${PROJECT_NAME}"
main = "workers/api/index.ts"
compatibility_date = "$(date +%Y-%m-%d)"
account_id = "${ACCOUNT_ID}"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "${PROJECT_NAME}-db"
database_id = "${DB_ID}"

# R2 Storage
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "${PROJECT_NAME}-assets"

# KV Namespace
[[kv_namespaces]]
binding = "CONFIG"
id = "${KV_ID}"

# Environment Variables
[vars]
ENVIRONMENT = "production"

# Production Environment
[env.production]
name = "${PROJECT_NAME}-production"
vars = { ENVIRONMENT = "production" }
EOF

success "wrangler.toml updated with resource IDs"

# Step 6: Run Database Migration
step "🗄️  Running database migration..."
if [ -f "./schema/full-schema.sql" ]; then
    if npx wrangler d1 execute "${PROJECT_NAME}-db" --file=./schema/full-schema.sql; then
        success "Database schema created successfully"
    else
        error "Database migration failed. Check schema file."
        info "Continuing anyway..."
    fi
else
    info "No schema file found at ./schema/full-schema.sql - skipping migration"
fi

# Step 7: Activate Comprehensive API Router
step "🔄 Activating API router..."
if [ -f "workers/api/new-index.ts" ]; then
    cp workers/api/new-index.ts workers/api/index.ts
    success "API router activated"
else
    info "No new-index.ts found - using existing index.ts"
fi

# Step 8: Set JWT Secret
step "🔐 Setting JWT secret..."
echo "Enter a secure random string for JWT_SECRET (or press Enter for auto-generated):"
read -r JWT_INPUT

if [ -z "$JWT_INPUT" ]; then
    # Generate random JWT secret
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || date +%s | sha256sum | base64 | head -c 32)
    info "Auto-generated JWT secret"
    echo "$JWT_SECRET" | npx wrangler secret put JWT_SECRET
else
    echo "$JWT_INPUT" | npx wrangler secret put JWT_SECRET
fi
success "JWT secret configured"

# Step 9: Deploy Workers API
step "⚙️  Deploying Workers API..."
if npx wrangler deploy; then
    success "Workers API deployed successfully"
else
    error "Workers deployment failed"
    info "Check error messages above and fix issues before continuing"
    exit 1
fi

# Step 10: Build Frontend
step "🏗️  Building frontend..."
if [ -f "package.json" ]; then
    if npm run build; then
        success "Frontend build completed"
    else
        error "Frontend build failed"
        info "Check error messages above"
        exit 1
    fi
else
    info "No package.json found - skipping frontend build"
fi

# Step 11: Deploy to Cloudflare Pages
step "🌐 Deploying to Cloudflare Pages..."
if [ -d "out" ]; then
    if npx wrangler pages deploy out --project-name="${PROJECT_NAME}" --commit-dirty=true; then
        success "Deployed to Cloudflare Pages"
    else
        error "Pages deployment failed"
        info "You may need to create the Pages project first in Cloudflare dashboard"
    fi
else
    info "No 'out' directory found - skipping Pages deployment"
    info "If using a different output directory, deploy manually with:"
    info "  npx wrangler pages deploy <directory> --project-name=${PROJECT_NAME} --commit-dirty=true"
fi

# Final Summary
echo -e "\n${GREEN}"
cat << "EOF"
╔══════════════════════════════════════════════════════════╗
║   🎉 DEPLOYMENT COMPLETE!                                ║
╚══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

echo "📍 Your Resources:"
echo "   • Website: https://${PROJECT_NAME}.pages.dev"
echo "   • API: https://${PROJECT_NAME}.[your-subdomain].workers.dev"
echo "   • Database: ${PROJECT_NAME}-db (ID: ${DB_ID})"
echo "   • Storage: ${PROJECT_NAME}-assets"
echo "   • KV Store: CONFIG (ID: ${KV_ID})"
echo ""
echo "🧪 Test Your API:"
echo "   curl https://${PROJECT_NAME}.[subdomain].workers.dev/api/health"
echo ""
echo "✅ Next Steps:"
echo "   1. Create admin user: POST /api/auth/register"
echo "   2. Test login: POST /api/auth/login"
echo "   3. Set optional secrets (Stripe, OpenAI, etc.)"
echo "   4. Configure custom domain (optional)"
echo ""
echo "📚 Documentation:"
echo "   • See FULL_PROJECT_SUMMARY.md for complete details"
echo "   • See TURNKEY_DEPLOYMENT_GUIDE.md for future deployments"
echo ""
echo "Deployment completed at: $(date '+%Y-%m-%d %H:%M:%S')"
