# ==========================================
# Turnkey SaaS Platform Deployment Script
# PowerShell Version for Windows
# ==========================================
#
# This script automates the complete deployment of a full-stack SaaS platform to Cloudflare.
#
# Prerequisites:
# - Node.js installed
# - Git installed
# - Cloudflare account
# - Logged in via: npx wrangler login
#
# Usage:
#   .\deploy-turnkey.ps1 -ProjectName "my-saas-app"
#
# ==========================================

param(
    [Parameter(Mandatory=$true)]
    [string]$ProjectName,

    [Parameter(Mandatory=$false)]
    [string]$Branch = "main"
)

# Color functions
function Write-Step { param($msg) Write-Host "`n$msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "✅ $msg" -ForegroundColor Green }
function Write-Error { param($msg) Write-Host "❌ $msg" -ForegroundColor Red }
function Write-Info { param($msg) Write-Host "ℹ️  $msg" -ForegroundColor Yellow }

Write-Host @"
╔══════════════════════════════════════════════════════════╗
║   🚀 Turnkey SaaS Platform Deployment                   ║
║   Project: $ProjectName
║   Branch: $Branch
╚══════════════════════════════════════════════════════════╝
"@ -ForegroundColor Magenta

# Check if logged in to Cloudflare
Write-Step "Checking Cloudflare authentication..."
try {
    $whoami = npx wrangler whoami 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Not logged in to Cloudflare. Run: npx wrangler login"
        exit 1
    }
    Write-Success "Authenticated with Cloudflare"
} catch {
    Write-Error "Wrangler CLI not available. Install dependencies first: npm install"
    exit 1
}

# Step 1: Create D1 Database
Write-Step "📊 Creating D1 Database: $ProjectName-db"
try {
    npx wrangler d1 create "$ProjectName-db" 2>$null
    Write-Success "D1 Database created (or already exists)"
} catch {
    Write-Info "Database might already exist, continuing..."
}

# Get database ID
Write-Info "Fetching database ID..."
$dbList = npx wrangler d1 list --json | ConvertFrom-Json
$database = $dbList | Where-Object { $_.name -eq "$ProjectName-db" } | Select-Object -First 1
$dbId = $database.database_id

if (-not $dbId) {
    Write-Error "Could not find database ID. Please check Cloudflare dashboard."
    Write-Info "Continuing anyway - you may need to update wrangler.toml manually"
    $dbId = "REPLACE_WITH_YOUR_DB_ID"
} else {
    Write-Success "Database ID: $dbId"
}

# Step 2: Create R2 Bucket
Write-Step "📦 Creating R2 Bucket: $ProjectName-assets"
try {
    npx wrangler r2 bucket create "$ProjectName-assets" 2>$null
    Write-Success "R2 Bucket created (or already exists)"
} catch {
    Write-Info "Bucket might already exist, continuing..."
}

# Step 3: Create KV Namespace
Write-Step "🔑 Creating KV Namespace: CONFIG"
try {
    npx wrangler kv namespace create CONFIG 2>$null
    Write-Success "KV Namespace created (or already exists)"
} catch {
    Write-Info "KV namespace might already exist, continuing..."
}

# Get KV ID
Write-Info "Fetching KV namespace ID..."
$kvList = npx wrangler kv namespace list --json | ConvertFrom-Json
$namespace = $kvList | Where-Object { $_.title -like "*CONFIG*" } | Select-Object -First 1
$kvId = $namespace.id

if (-not $kvId) {
    Write-Error "Could not find KV namespace ID. Please check Cloudflare dashboard."
    Write-Info "Continuing anyway - you may need to update wrangler.toml manually"
    $kvId = "REPLACE_WITH_YOUR_KV_ID"
} else {
    Write-Success "KV Namespace ID: $kvId"
}

# Step 4: Get Account ID
$accountId = ($whoami | Select-String -Pattern "Account ID: ([a-f0-9]+)" | ForEach-Object { $_.Matches.Groups[1].Value })
if (-not $accountId) {
    Write-Info "Could not auto-detect account ID from wrangler whoami"
    $accountId = "REPLACE_WITH_YOUR_ACCOUNT_ID"
}

# Step 5: Update wrangler.toml
Write-Step "📝 Updating wrangler.toml configuration..."

$wranglerToml = @"
# Cloudflare Workers Configuration for $ProjectName
# Auto-generated by deploy-turnkey.ps1

name = "$ProjectName"
main = "workers/api/index.ts"
compatibility_date = "$(Get-Date -Format 'yyyy-MM-dd')"
account_id = "$accountId"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "$ProjectName-db"
database_id = "$dbId"

# R2 Storage
[[r2_buckets]]
binding = "ASSETS"
bucket_name = "$ProjectName-assets"

# KV Namespace
[[kv_namespaces]]
binding = "CONFIG"
id = "$kvId"

# Environment Variables
[vars]
ENVIRONMENT = "production"

# Production Environment
[env.production]
name = "$ProjectName-production"
vars = { ENVIRONMENT = "production" }
"@

Set-Content -Path "wrangler.toml" -Value $wranglerToml
Write-Success "wrangler.toml updated with resource IDs"

# Step 6: Run Database Migration
Write-Step "🗄️  Running database migration..."
if (Test-Path "./schema/full-schema.sql") {
    try {
        npx wrangler d1 execute "$ProjectName-db" --file=./schema/full-schema.sql
        Write-Success "Database schema created successfully"
    } catch {
        Write-Error "Database migration failed. Check schema file."
        Write-Info "Continuing anyway..."
    }
} else {
    Write-Info "No schema file found at ./schema/full-schema.sql - skipping migration"
}

# Step 7: Activate Comprehensive API Router
Write-Step "🔄 Activating API router..."
if (Test-Path "workers/api/new-index.ts") {
    Copy-Item "workers/api/new-index.ts" "workers/api/index.ts" -Force
    Write-Success "API router activated"
} else {
    Write-Info "No new-index.ts found - using existing index.ts"
}

# Step 8: Set JWT Secret
Write-Step "🔐 Setting JWT secret..."
Write-Host "Enter a secure random string for JWT_SECRET (or press Enter for auto-generated):" -ForegroundColor Yellow
$jwtInput = Read-Host
if ([string]::IsNullOrWhiteSpace($jwtInput)) {
    # Generate random JWT secret
    $jwtSecret = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 32 | ForEach-Object {[char]$_})
    Write-Info "Auto-generated JWT secret"
    $jwtSecret | npx wrangler secret put JWT_SECRET
} else {
    $jwtInput | npx wrangler secret put JWT_SECRET
}
Write-Success "JWT secret configured"

# Step 9: Deploy Workers API
Write-Step "⚙️  Deploying Workers API..."
try {
    npx wrangler deploy
    Write-Success "Workers API deployed successfully"
} catch {
    Write-Error "Workers deployment failed"
    Write-Info "Check error messages above and fix issues before continuing"
    exit 1
}

# Step 10: Build Frontend
Write-Step "🏗️  Building frontend..."
if (Test-Path "package.json") {
    try {
        npm run build
        Write-Success "Frontend build completed"
    } catch {
        Write-Error "Frontend build failed"
        Write-Info "Check error messages above"
        exit 1
    }
} else {
    Write-Info "No package.json found - skipping frontend build"
}

# Step 11: Deploy to Cloudflare Pages
Write-Step "🌐 Deploying to Cloudflare Pages..."
if (Test-Path "out") {
    try {
        npx wrangler pages deploy out --project-name=$ProjectName --commit-dirty=$true
        Write-Success "Deployed to Cloudflare Pages"
    } catch {
        Write-Error "Pages deployment failed"
        Write-Info "You may need to create the Pages project first in Cloudflare dashboard"
    }
} else {
    Write-Info "No 'out' directory found - skipping Pages deployment"
    Write-Info "If using a different output directory, deploy manually with:"
    Write-Info "  npx wrangler pages deploy <directory> --project-name=$ProjectName --commit-dirty=`$true"
}

# Final Summary
Write-Host @"

╔══════════════════════════════════════════════════════════╗
║   🎉 DEPLOYMENT COMPLETE!                                ║
╚══════════════════════════════════════════════════════════╝

📍 Your Resources:
   • Website: https://$ProjectName.pages.dev
   • API: https://$ProjectName.[your-subdomain].workers.dev
   • Database: $ProjectName-db (ID: $dbId)
   • Storage: $ProjectName-assets
   • KV Store: CONFIG (ID: $kvId)

🧪 Test Your API:
   curl https://$ProjectName.[subdomain].workers.dev/api/health

✅ Next Steps:
   1. Create admin user: POST /api/auth/register
   2. Test login: POST /api/auth/login
   3. Set optional secrets (Stripe, OpenAI, etc.)
   4. Configure custom domain (optional)

📚 Documentation:
   • See FULL_PROJECT_SUMMARY.md for complete details
   • See TURNKEY_DEPLOYMENT_GUIDE.md for future deployments

"@ -ForegroundColor Green

Write-Host "Deployment completed at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
